config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :products

  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true, greater_than: 0}
  has_many :reviews
  has_attached_file :image, styles: { large: "600x600", medium: "300x300>", thumb: "150x150#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :description, length: {maximum: 1000, too_long: "%{count} characters is the maximum allowed. "}

  SIZE = %W{XS S M L XL}
  COLOR = %W{ Black White Grey Orange Purple Blue Yellow Multi }

  def formatted_price
   price_in_dollars = price_in_cents.to_f / 100
   format("%.2f", price_in_dollars)
 end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @review = Review.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :size, :brand, :color, :price_in_cents, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrbanShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Shrikhand" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product,html: { multipart: true }, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>


 <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <label>Price:</label>
    <%= form.number_field :price_in_cents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product ,class: "btn-flat"%>
<%= link_to 'Back', products_path ,class: "btn-flat"%>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Urban Renewal</h1>


<table class="product-table striped responsive-table">
  <!-- <thead align="left">
    <tr>
      <th></th>
      <th>Item</th>
      <th>Description</th>
      <th>Size</th>
      <th>Brand</th>
      <th>Color</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= image_tag product.image.url(:medium) %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.size %></td>
        <td><%= product.brand %></td>
        <td><%= product.color %></td>
        <td>$<%= product.price_in_cents %></td>
        <td><%= link_to 'Show', product , class: "main btn-flat"%></td>
        <td><%= link_to 'Edit', edit_product_path(product),class: "main btn-flat"%></td>
        <td><%= link_to 'Destroy', product, class: "main btn-flat", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class: "new-product btn-flat" %>

app/views/products/new.html.erb
<h1>Urban Renewal</h1>
<h5>New Product</h5>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class: "btn-flat"%>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Urban Renewal</h1>


<div class="left">
<%= image_tag @product.image.url(:large) %>
</div>

<div class="row">
<div class="col s2 m4 l6 ">
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.size %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @product.price_in_cents %>
</p>

<h5>Reviews</h5>
<hr/>
<% @product.reviews.each do |review| %>
  <p>
    <%= review.comment %>
    <br>
    <span class="date">Added on: <%= review.created_at.strftime("%Y-%m-%d") %></span>
  </p>
<% end %>
</div>
</div>

<h5>New Review</h5>
<hr/>
<%= render 'reviews/form' %>

<%= link_to 'Edit', edit_product_path(@product), class: "btn-flat" %>
<%= link_to 'Back', products_path, class: "btn-flat" %>

app/views/reviews/_form.html.erb
<%= form_with(model: @review, local: true) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :comment, placeholder: "Write a review" %>
  </div>

  <% if @product.nil? %>
   <div class="field">
     <%= form.label :product_id %><br>
     <%= form.text_field :product_id %>
   </div>

 <% else %>
   <%= form.hidden_field :product_id, value: @product.id %>

 <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>
<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<p class="review-header">Reviews</p>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="reviews">
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.product %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h4>New review</h4>
<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product.name %>

</p>

<%= link_to 'Edit', edit_review_path(@review) %> |

<% if @review.product.nil? %>
  <%= link_to 'Back', @review.product %>

<% else %>
  <%= link_to 'Back', @review.product %>
<% end %>